language: ruby
cache: bundler
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 67bd12d38e2ebb8be9df65f57a080a4fb436739c75ed859a82cd3267807d38ba
services:
  - postgresql
after_success:
  - bundle exec codeclimate-test-reporter
