development: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 5000
  database: api_guardian_dev
  username: apshoemaker
  password:
  host: localhost

test:
  <<: *default
  database: api_guardian_test
